name: shelf_cookie
version: 2.0.0
description: >-
  Cookie parser middleware for the Shelf ecosystem.
  Reads cookies in request, sets cookies in response.
author: izolate <izolate@gmail.com>
homepage: https://github.com/izolate/shelf-cookie
documentation: https://github.com/izolate/shelf-cookie/blob/master/README.md

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  shelf: ^1.0.0
  collection: ^1.15.0

dev_dependencies:
  test: ^1.16.6
